// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlanReview.Api.Data;

#nullable disable

namespace PlanReview.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822072636_MidYearSubmitAndRatingsReleased")]
    partial class MidYearSubmitAndRatingsReleased
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PlanReview.Api.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompanyTraitId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Manager1Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Manager2Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTraitId");

                    b.HasIndex("ReviewId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("PlanReview.Api.Models.CompanyTrait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CompanyTraits");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Function", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("PlanReview.Api.Models.FutureSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("FutureSkills");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achievable")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CompanyTraitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Measurable")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relevant")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specific")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusComment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeBound")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTraitId");

                    b.HasIndex("ReviewId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FunctionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MidYearReflection")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MidYearSubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MidYearUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewCycleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedPeerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelfSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SelectedPeerId");

                    b.HasIndex("ReviewCycleId", "DeveloperId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("PlanReview.Api.Models.ReviewCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HalfYearlyDueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HalfYearlyReleased")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("HalfYearlyReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RatingsReleased")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RatingsReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReviewCycles");
                });

            modelBuilder.Entity("PlanReview.Api.Models.ReviewReviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewerType")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ReviewId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("ReviewReviewers");
                });

            modelBuilder.Entity("PlanReview.Api.Models.ReviewerAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Improvements")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("OverallRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewerType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Strengths")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ReviewId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("ReviewerAssessments");
                });

            modelBuilder.Entity("PlanReview.Api.Models.ReviewerSkillRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewerAssessmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerAssessmentId");

                    b.HasIndex("SkillId");

                    b.ToTable("ReviewerSkillRatings");
                });

            modelBuilder.Entity("PlanReview.Api.Models.RndImprovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("RndImprovements");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FunctionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PlanReview.Api.Models.RoleSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("RoleId", "SkillId")
                        .IsUnique();

                    b.ToTable("RoleSkills");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("PlanReview.Api.Models.SkillRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelfRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillRatings");
                });

            modelBuilder.Entity("PlanReview.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FunctionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Achievement", b =>
                {
                    b.HasOne("PlanReview.Api.Models.CompanyTrait", "CompanyTrait")
                        .WithMany()
                        .HasForeignKey("CompanyTraitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlanReview.Api.Models.Review", "Review")
                        .WithMany("Achievements")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyTrait");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("PlanReview.Api.Models.FutureSkill", b =>
                {
                    b.HasOne("PlanReview.Api.Models.Review", "Review")
                        .WithMany("FutureSkills")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Goal", b =>
                {
                    b.HasOne("PlanReview.Api.Models.CompanyTrait", "CompanyTrait")
                        .WithMany()
                        .HasForeignKey("CompanyTraitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlanReview.Api.Models.Review", "Review")
                        .WithMany("Goals")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyTrait");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Notification", b =>
                {
                    b.HasOne("PlanReview.Api.Models.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Review", b =>
                {
                    b.HasOne("PlanReview.Api.Models.User", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlanReview.Api.Models.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId");

                    b.HasOne("PlanReview.Api.Models.ReviewCycle", "ReviewCycle")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanReview.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("PlanReview.Api.Models.User", "SelectedPeer")
                        .WithMany()
                        .HasForeignKey("SelectedPeerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");

                    b.Navigation("Function");

                    b.Navigation("ReviewCycle");

                    b.Navigation("Role");

                    b.Navigation("SelectedPeer");
                });

            modelBuilder.Entity("PlanReview.Api.Models.ReviewReviewer", b =>
                {
                    b.HasOne("PlanReview.Api.Models.Review", "Review")
                        .WithMany("Reviewers")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanReview.Api.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PlanReview.Api.Models.ReviewerAssessment", b =>
                {
                    b.HasOne("PlanReview.Api.Models.Review", "Review")
                        .WithMany("Assessments")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanReview.Api.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("PlanReview.Api.Models.ReviewerSkillRating", b =>
                {
                    b.HasOne("PlanReview.Api.Models.ReviewerAssessment", "ReviewerAssessment")
                        .WithMany("SkillRatings")
                        .HasForeignKey("ReviewerAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanReview.Api.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewerAssessment");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PlanReview.Api.Models.RndImprovement", b =>
                {
                    b.HasOne("PlanReview.Api.Models.Review", "Review")
                        .WithMany("RndImprovements")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Role", b =>
                {
                    b.HasOne("PlanReview.Api.Models.Function", "Function")
                        .WithMany("Roles")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");
                });

            modelBuilder.Entity("PlanReview.Api.Models.RoleSkill", b =>
                {
                    b.HasOne("PlanReview.Api.Models.Role", "Role")
                        .WithMany("RoleSkills")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanReview.Api.Models.Skill", "Skill")
                        .WithMany("RoleSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PlanReview.Api.Models.SkillRating", b =>
                {
                    b.HasOne("PlanReview.Api.Models.Review", "Review")
                        .WithMany("SkillRatings")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlanReview.Api.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("PlanReview.Api.Models.User", b =>
                {
                    b.HasOne("PlanReview.Api.Models.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlanReview.Api.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Function");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Function", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Review", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Assessments");

                    b.Navigation("FutureSkills");

                    b.Navigation("Goals");

                    b.Navigation("Reviewers");

                    b.Navigation("RndImprovements");

                    b.Navigation("SkillRatings");
                });

            modelBuilder.Entity("PlanReview.Api.Models.ReviewCycle", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PlanReview.Api.Models.ReviewerAssessment", b =>
                {
                    b.Navigation("SkillRatings");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Role", b =>
                {
                    b.Navigation("RoleSkills");
                });

            modelBuilder.Entity("PlanReview.Api.Models.Skill", b =>
                {
                    b.Navigation("RoleSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
